### ISSUE TITLE
Explanation about icon/symbol meaning.

### ISSUE THREAD

**Issue by Ahmad-Amsyar** [zacharee/CameraXInfo#3]
Since this app using symbol to show the availability, I hope there is a short explanation or notice what the symbol means in the app.

What I know:

✅  Available.
❌  Not available.

The symbol im not sure:
⚪  And ❔

**Comment by es0329** [comment]
⚪ [Not Applicable](https://github.com/zacharee/CameraXInfo/blob/01613cebca4d675bb9ddb938765f8b545d2019f7/app/src/main/java/dev/zwander/cameraxinfo/ui/components/SupportStateIcon.kt#L103-L110).
❔ [Unknown](https://github.com/zacharee/CameraXInfo/blob/01613cebca4d675bb9ddb938765f8b545d2019f7/app/src/main/java/dev/zwander/cameraxinfo/ui/components/SupportStateIcon.kt#L111-L118).

**Comment by Ahmad-Amsyar** [comment]
> ⚪ [Not Applicable](https://github.com/zacharee/CameraXInfo/blob/01613cebca4d675bb9ddb938765f8b545d2019f7/app/src/main/java/dev/zwander/cameraxinfo/ui/components/SupportStateIcon.kt#L103-L110).
> ❔ [Unknown](https://github.com/zacharee/CameraXInfo/blob/01613cebca4d675bb9ddb938765f8b545d2019f7/app/src/main/java/dev/zwander/cameraxinfo/ui/components/SupportStateIcon.kt#L111-L118).

Thank you for explanation.
